export const DEAD_CIRCUIT_ENEMY_PLAN = {
  name: "IRON PROCESSION",
  intent: "Screen Beta, counter the breach, then sever the gantry.",
  formations: [
    { id: "aegis", number: "E1", name: "AEGIS COHORT", start: { x: 94, y: 5 }, end: { x: 76, y: 18 }, actionAt: 90 },
    { id: "cinder", number: "E2", name: "CINDER LANCE", start: { x: 96, y: 36 }, end: { x: 76, y: 48 }, actionAt: 225 },
    { id: "pursuit", number: "E3", name: "OATH PURSUIT", start: { x: 94, y: 61 }, end: { x: 88, y: 23 }, actionAt: 330 },
  ],
  stages: [
    {
      id: "screen",
      formationId: "aegis",
      label: "BETA SCREEN",
      creates: "FORTIFIED LANE",
      intelligence: "KNOWN",
      counterCapabilities: ["CONTROL", "DENIAL"],
      pressure: { type: "SUPPRESSION", target: "cohesion", strength: 3 },
      resistance: 7,
      counteredBy: ["FURNACE DRAGNET", "ASHEN CORDON"],
      impact: { reactorDelay: 15 },
      consequence: "Reactor thrust delayed +00:15",
    },
    {
      id: "counter",
      formationId: "cinder",
      label: "OATH COUNTER",
      uses: "FORTIFIED LANE",
      creates: "COUNTERFIRE",
      intelligence: "UNCERTAIN",
      counterCapabilities: ["BREACH", "SHOCK"],
      pressure: { type: "FIREPOWER", target: "armor", strength: 4 },
      resistance: 8,
      counteredBy: ["EXECUTION BREACH", "THERMAL BREACH", "FORCED ENTRY", "FIELD REARM", "COVERED ADVANCE", "LOCKED BREACH"],
      impact: { missionDelay: 15 },
      consequence: "Extraction timetable delayed +00:15",
    },
    {
      id: "sever",
      formationId: "pursuit",
      label: "GANTRY SEVER",
      uses: "COUNTERFIRE",
      creates: "CUT OFF",
      intelligence: "UNKNOWN",
      counterCapabilities: ["RECOVERY", "HOLD"],
      pressure: { type: "PURSUIT", target: "mobility", strength: 5 },
      resistance: 8,
      counteredBy: ["ARMORED EVAC", "HOT RECOVERY", "BREACH RECOVERY", "LOCKSTEP HOLD"],
      impact: { recoveryLoss: 1 },
      consequence: "One formation cut off from extraction",
    },
  ],
};

export const ASHEN_PASSAGE_ENEMY_PLAN = {
  name: "BLACK LITANY",
  intent: "Blind the Ember Gates, silence the relay, then occupy the Void Lift.",
  formations: [
    { id: "veil", number: "E1", name: "VEIL ENGINES", start: { x: 95, y: 67 }, end: { x: 61, y: 23 }, actionAt: 90 },
    { id: "ward", number: "E2", name: "OATH WARD", start: { x: 97, y: 45 }, end: { x: 72, y: 39 }, actionAt: 225 },
    { id: "ascendant", number: "E3", name: "ASCENDANT GUARD", start: { x: 82, y: 3 }, end: { x: 89, y: 15 }, actionAt: 330 },
  ],
  stages: [
    {
      id: "veil",
      formationId: "veil",
      label: "ASH VEIL",
      creates: "BLINDED CORRIDOR",
      intelligence: "KNOWN",
      counterCapabilities: ["CONTROL", "COVER"],
      pressure: { type: "SIGNAL SHOCK", target: "cohesion", strength: 3 },
      resistance: 7,
      counteredBy: ["COVERED DRAG", "POWER WINCH", "FURNACE DRAGNET", "ASHEN CORDON", "MAGNETIC RELAY KEY", "VEIL FRACTURE", "FURNACE FEED"],
      impact: { reactorDelay: 15 },
      consequence: "Signal relay delayed +00:15",
    },
    {
      id: "silence",
      formationId: "ward",
      label: "FURNACE SILENCE",
      uses: "BLINDED CORRIDOR",
      creates: "RELAY LOCK",
      intelligence: "UNCERTAIN",
      counterCapabilities: ["BREACH", "DENIAL"],
      pressure: { type: "FIREPOWER", target: "armor", strength: 4 },
      resistance: 8,
      counteredBy: ["THERMAL BREACH", "COVERED ADVANCE", "LOCKED BREACH", "WEDGE & WALL", "LOCKSTEP HOLD", "FURNACE FEED"],
      impact: { missionDelay: 15 },
      consequence: "Void Lift opening delayed +00:15",
    },
    {
      id: "occupy",
      formationId: "ascendant",
      label: "LIFT OCCUPATION",
      uses: "RELAY LOCK",
      creates: "LIFT SEALED",
      intelligence: "UNKNOWN",
      counterCapabilities: ["RECOVERY", "HOLD"],
      pressure: { type: "OCCUPATION", target: "mobility", strength: 5 },
      resistance: 8,
      counteredBy: ["ARMORED EVAC", "HOT RECOVERY", "BREACH RECOVERY", "MOBILE RESUPPLY", "VOID LIFT BUBBLE"],
      impact: { recoveryLoss: 1 },
      consequence: "One formation sealed below the Void Lift",
    },
  ],
};

export const ENEMY_PLANS = {
  "dead-circuit": DEAD_CIRCUIT_ENEMY_PLAN,
  "ashen-passage": ASHEN_PASSAGE_ENEMY_PLAN,
};

export const enemyPlanFor = (operation) => ENEMY_PLANS[operation?.id] ?? DEAD_CIRCUIT_ENEMY_PLAN;
